server {
    listen 80;
    absolute_redirect off;
    
    # Redirigir la raíz a /simposio/
    location = / {
        return 301 /simposio/;
    }
    
    location = /simposio {
        return 301 /simposio/;
    }

    # Servir la aplicación de frontend
    location /simposio/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /simposio/index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
